In [118]:
import pandas as pd
import numpy as np

In [119]:
df=pd.read_csv("health_care.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [120]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [121]:
df["Outcome"].value_counts(dropna=False)

0    500
1    268
Name: Outcome, dtype: int64

In [122]:
X=df.iloc[:,:-1]
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [123]:
Y=df.iloc[:,-1]
Y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

# KNeighborsClassifier (KNN)

In [124]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(X, Y,stratify=Y, test_size=0.3, random_state=1)

In [125]:
X.shape, Y.shape

((768, 8), (768,))

In [126]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((537, 8), (537,), (231, 8), (231,))

In [127]:
from sklearn.neighbors import KNeighborsClassifier

knn_class=KNeighborsClassifier(n_neighbors=9)
knn_class.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=9)

In [128]:
y_predicted = knn_class.predict(x_test)
print(pd.DataFrame({"y_predicted": y_predicted,"y_test": y_test}).head(10))

     y_predicted  y_test
397            0       1
247            1       0
161            0       0
585            0       0
552            0       0
510            0       1
744            1       0
34             1       0
646            1       1
241            0       0


In [129]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, classification_report

In [130]:
#Danh gia mo hinh
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_predicted, labels = [0,1]),"\n") 


Confusion Matrix: 
[[126  24]
 [ 43  38]] 



In [131]:
acc = accuracy_score(y_test, y_predicted)*100
print("accurate_score")
print(acc,"\n")

accurate_score
70.995670995671 



In [132]:
print("Predicted")
print(precision_score(y_test, y_predicted, labels=[0,1], average=None)*100, "\n")
#Predicted cua lop 0 la : 74.55
#Predicted cua lop 1 la :61.29

Predicted
[74.55621302 61.29032258] 



In [133]:
print("Recall score")
print(recall_score(y_test, y_predicted, labels=[0,1], average=None)*100, "\n")
#Recall score cua lop 0 la : 84
#Recall score cua lop 1 la :46.91

Recall score
[84.         46.91358025] 



In [134]:
print("F1 score:")
print(f1_score(y_test, y_predicted, labels=[0,1], average=None)*100, "\n")
#F1 score score cua lop 0 la : 78.99
#F1 score cua lop 1 la :53.14

F1 score:
[78.9968652  53.14685315] 



In [135]:
print(classification_report(y_test, y_predicted))

              precision    recall  f1-score   support

           0       0.75      0.84      0.79       150
           1       0.61      0.47      0.53        81

    accuracy                           0.71       231
   macro avg       0.68      0.65      0.66       231
weighted avg       0.70      0.71      0.70       231



# DT classifler

In [136]:
from sklearn.tree import DecisionTreeClassifier

In [137]:
DT_class = DecisionTreeClassifier(criterion='entropy')
DT_class.fit(x_train,y_train)


DecisionTreeClassifier(criterion='entropy')

In [138]:
y_predicted = DT_class.predict(x_test)
print(pd.DataFrame({"y_predicted": y_predicted,"y_test": y_test}).head(10))

     y_predicted  y_test
397            0       1
247            1       0
161            0       0
585            0       0
552            0       0
510            0       1
744            1       0
34             0       0
646            1       1
241            0       0


In [139]:
print("Confusition matrix")
print(confusion_matrix(y_test, y_predicted, labels = [0,1]),"\n") 

Confusition matrix
[[126  24]
 [ 32  49]] 



In [140]:
acc = accuracy_score(y_test, y_predicted)*100
print("accurate_score")
print(acc,"\n")

accurate_score
75.75757575757575 



In [141]:
print("Predicted")
print(precision_score(y_test, y_predicted, labels=[0,1], average=None)*100, "\n")
#Predicted cua lop 0 la : 77.84
#Predicted cua lop 1 la :63.01

Predicted
[79.74683544 67.12328767] 



In [142]:
print("Recall score")
print(recall_score(y_test, y_predicted, labels=[0,1], average=None)*100, "\n")
#Recall score cua lop 0 la : 82
#Recall score cua lop 1 la :56.79

Recall score
[84.         60.49382716] 



In [143]:
print("F1 score:")
print(f1_score(y_test, y_predicted, labels=[0,1], average=None)*100, "\n")
#F1 score score cua lop 0 la : 79.87
#F1 score cua lop 1 la :59.74

F1 score:
[81.81818182 63.63636364] 



In [144]:
print(classification_report(y_test, y_predicted))

              precision    recall  f1-score   support

           0       0.80      0.84      0.82       150
           1       0.67      0.60      0.64        81

    accuracy                           0.76       231
   macro avg       0.73      0.72      0.73       231
weighted avg       0.75      0.76      0.75       231



# Gaussian Naive Bayes (Gaussian NB)

In [145]:
from sklearn.naive_bayes import GaussianNB
gnb_class = GaussianNB()
gnb_class.fit(x_train, y_train)

GaussianNB()

In [146]:
y_predicted = gnb_class.predict(x_test)
print(pd.DataFrame({"y_predicted": y_predicted,"y_test": y_test}).head(10))

     y_predicted  y_test
397            0       1
247            1       0
161            0       0
585            0       0
552            0       0
510            0       1
744            1       0
34             0       0
646            0       1
241            0       0


In [147]:
print("Confusition matrix")
print(confusion_matrix(y_test, y_predicted, labels = [0,1]),"\n") 

Confusition matrix
[[120  30]
 [ 37  44]] 



In [148]:
acc = accuracy_score(y_test, y_predicted)*100
print("accurate_score")
print(acc,"\n")

accurate_score
70.995670995671 



In [149]:
print("Predicted")
print(precision_score(y_test, y_predicted, labels=[0,1], average=None)*100, "\n")
#Predicted cua lop 0 la : 77.84
#Predicted cua lop 1 la :63.01

Predicted
[76.43312102 59.45945946] 



In [150]:
print("Recall score")
print(recall_score(y_test, y_predicted, labels=[0,1], average=None)*100, "\n")
#Recall score cua lop 0 la : 82
#Recall score cua lop 1 la :56.79

Recall score
[80.         54.32098765] 



In [151]:
print("F1 score:")
print(f1_score(y_test, y_predicted, labels=[0,1], average=None)*100, "\n")
#F1 score score cua lop 0 la : 79.87
#F1 score cua lop 1 la :59.74

F1 score:
[78.17589577 56.77419355] 



In [152]:
print(classification_report(y_test, y_predicted))

              precision    recall  f1-score   support

           0       0.76      0.80      0.78       150
           1       0.59      0.54      0.57        81

    accuracy                           0.71       231
   macro avg       0.68      0.67      0.67       231
weighted avg       0.70      0.71      0.71       231

